import { streamText, tool, generateText, ToolResult } from 'ai'; // Removed ToolInvocation import
import { google } from '@ai-sdk/google';
import { anthropic } from '@ai-sdk/anthropic';
import { z } from 'zod';
import { Message as AIMessage } from '@ai-sdk/react'; // Import Message type


// --- Main Website Generator Tool Schema ---
const websiteGeneratorSchema = z.object({
  currentHtml: z.string().nullable().optional().describe('The current HTML content of the website, if it exists. Can be null if starting fresh.'),
  updateInstructions: z.string().describe('Specific instructions based on the latest user input for how to update the website (e.g., "Update the overview section with this summary", "Change the main title to \'Project Dashboard\'").'),
});

// --- System Prompt for Full HTML Generation ---
const websiteGenerationSystemPrompt = `You are an AI assistant responsible for generating or updating a complete HTML document based on user instructions.
Analyze the 'Update Instructions' and the 'Current HTML' (if provided). If 'Current HTML' is null or empty, generate the initial HTML based *only* on the 'Update Instructions'.
Generate the *complete, updated HTML content* that incorporates the requested changes or creates the initial structure.
Output ONLY the raw, complete, updated HTML string. Do not include any explanations, markdown formatting, or anything other than the HTML code itself. Ensure the output is a valid HTML document starting with <!DOCTYPE html>.


Here is the template for the HTML:
\`\`\`html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AI Generated Page</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js"></script>
  <style>
    body { background-color: #ffffff; color: #333333; }
    .section { background-color: #f5f5f5; border-radius: 6px; margin-bottom: 1.5rem; }
    .title, .subtitle { color: #333333; }
    .box { background-color: #ffffff; color: #333333; border: 1px solid #e0e0e0; }
    .footer { background-color: #f5f5f5; color: #666666; }
    #error-message-container { color: #ff3860; margin-top: 1rem; text-align: center; }
  </style>
</head>
<body>
  <!-- Header Section -->
  <section class="hero" id="header-section">
    <div class="hero-body">
      <div class="container">
        <h1 class="title" id="main-title">AI Generated Page</h1>
        <h2 class="subtitle" id="main-subtitle">Content being generated...</h2>
      </div>
    </div>
  </section>

  <!-- Main Content Area -->
  <main class="container section" id="main-content-area">
    <!-- Content will be dynamically inserted here by the AI -->
    <p>Loading content...</p>
  </main>

  <!-- Error Message Area -->
  <div class="container" id="error-message-container">
    <!-- Errors will be displayed here -->
  </div>

  <!-- Footer -->
  <footer class="footer" id="footer-section">
    <div class="content has-text-centered">
      <p id="footer-content">Generated by AI</p>
    </div>
  </footer>
</body>
</html>
\`\`\`

**IMPORTANT RESTRICTIONS:**
*   Do NOT invent dynamic data (prices, stats, news, etc.) unless explicitly provided. Use placeholders like "[Current Price]", "[Market Cap]", "[News Headline 1]" or descriptive text like "Chart loading...". Focus on HTML structure.
*   Do NOT use local image paths (e.g., '/img/...') or invent image URLs. Only use external URLs if relevant and certain they exist, otherwise omit images or use placeholders.
*   When adding JavaScript (\`<script>\` tags), do NOT use \`import\`. Assume libraries (like Chart.js) are globally available via CDN (e.g., \`new Chart(...)\`).`;


export async function POST(req: Request) {
  console.log("Entering POST /api/chat");
  try {
    // Parse the request body once
    const requestBody = await req.json();
    const { messages, currentHtml: requestHtml }: {
      messages: AIMessage[],
      currentHtml?: string
    } = requestBody;

    // Log request details
    console.log(`[Backend] Request received with currentHtml: ${requestHtml ? 'present' : 'not present'}`);
    console.log(`[Backend] Request HTML length: ${requestHtml?.length || 0}`);
    console.log(`[Backend] Request HTML preview: ${requestHtml ? requestHtml.substring(0, 100) + '...' : 'null'}`);
    console.log(`[Backend] Latest message: ${messages[messages.length - 1].content}`);

    // Find the last tool_result for 'websiteGenerator' to get the latest HTML
    let latestHtml: string | null = null;
    
    // First, check if currentHtml is provided in the request body
    if (requestHtml) {
        console.log("[Backend] Found HTML in request body");
        latestHtml = requestHtml;
        console.log(`[Backend] Using HTML from request body, length: ${requestHtml.length}`);
    }
    // If not found in request body, search in messages
    else {
        console.log("[HTML Finder] Searching for HTML in messages");
        for (let i = messages.length - 1; i >= 0; i--) {
            const msg = messages[i];
            console.log(`[HTML Finder] Checking message index ${i}, role: ${msg.role}`);
            
            // Check for parts in assistant messages (using the newer parts API instead of toolInvocations)
            if (msg.role === 'assistant' && msg.parts && Array.isArray(msg.parts)) {
                console.log(`[HTML Finder] Found assistant message with parts at index ${i}`);
                
                // Find websiteGenerator tool result in parts
                const websiteGenPart = msg.parts.find(
                    (part) =>
                        part.type === 'tool-invocation' &&
                        part.toolInvocation.toolName === 'websiteGenerator' &&
                        part.toolInvocation.state === 'result'
                );
                
                if (websiteGenPart &&
                    websiteGenPart.type === 'tool-invocation' &&
                    websiteGenPart.toolInvocation.state === 'result') {
                    console.log(`[HTML Finder] Found websiteGenerator part with state 'result'`);
                    
                    // Access the result from the toolInvocation property
                    const resultData = websiteGenPart.toolInvocation.result as { htmlContent?: string };
                    if (resultData && resultData.htmlContent) {
                        latestHtml = resultData.htmlContent;
                        console.log(`[HTML Finder] Successfully extracted htmlContent from tool result at index ${i}`);
                        break;
                    }
                }
            }
            
            // We no longer need to check for legacy 'tool' role messages or toolInvocations
            // The HTML state is now properly extracted from parts in assistant messages
        }
        
        if (!latestHtml) {
           console.log("[Backend] No previous HTML state found in messages.");
       } else {
           console.log(`[Backend] Found HTML in messages, length: ${latestHtml.length}`);
       }
    }

    // Check if the latest message is from the user and we have HTML to update
    const latestMessage = messages[messages.length - 1];
    // Removed redundant updatedMessages declaration
    
   // Removed direct tool call logic. All generation/updates will go through streamText and the websiteGenerator tool.
   const updatedMessages = messages; // Use original messages
    
    console.log(`[Backend] HTML state before processing: Found: ${latestHtml ? 'Yes' : 'No'}, Size: ${latestHtml ? latestHtml.length : 0} chars`);
    console.log(`[Backend] HTML preview: ${latestHtml ? latestHtml.substring(0, 100) + '...' : 'null'}`);
    
    // Modify the system prompt to include instructions about the HTML
    const systemPrompt = `You are a helpful AI assistant. You can use tools to perform specific tasks, like generating or updating website content based on the conversation.

When asked to create or modify a website, first assess if the request is clear and detailed enough. If the request is ambiguous or lacks necessary details, ask clarifying questions before proceeding or using the 'websiteGenerator' tool.

Once the requirements are clear, use the 'websiteGenerator' tool to perform the task. Explain the changes you are making via the tool. Do not output raw HTML in your main response.

IMPORTANT: When using the websiteGenerator tool, ALWAYS pass the most recent HTML state (if available from previous steps or the request body) as the 'currentHtml' parameter. If no previous HTML exists, pass 'null'. The tool's execute function will handle finding the latest state.

IMPORTANT: When using the websiteGenerator, ensure the AI does not invent dynamic data (like prices, stats, news). It should use clear placeholders (e.g., [Current Price], [Market Cap]) or descriptive text where real data would go.`;
    
    const result = streamText({
      model: anthropic('claude-3-7-sonnet-20250219'), // Model for main chat interaction
      system: systemPrompt,
      messages: updatedMessages, // Use the updated messages array that includes the direct tool call result
      tools: {
        websiteGenerator: tool({
          description: 'Generates or updates the website HTML based on user input and conversation context. Use this tool for all website modifications.',
          parameters: websiteGeneratorSchema,
          execute: async ({ currentHtml, updateInstructions }) => {
            console.log(`[websiteGenerator] Entering execute`);
            console.log(`[websiteGenerator] Received updateInstructions: ${updateInstructions}`);
            console.log(`[websiteGenerator] currentHtml parameter: ${currentHtml ? 'provided' : 'not provided'}`);
            console.log(`[websiteGenerator] currentHtml length: ${currentHtml?.length || 0}`);
            console.log(`[websiteGenerator] latestHtml from state: ${latestHtml ? 'found' : 'not found'}`);
            console.log(`[websiteGenerator] latestHtml length: ${latestHtml?.length || 0}`);
            
            // Force use of latestHtml if currentHtml is not provided but latestHtml exists
            if (!currentHtml && latestHtml) {
                console.log(`[websiteGenerator] Overriding currentHtml with latestHtml from state`);
                currentHtml = latestHtml;
            }
            
            // Use 'let' so it can be reassigned by the sub-tool execute functions
           // Determine the HTML to use: parameter first, then state, then null
           let workingHtml: string | null = null;
           if (currentHtml) {
               workingHtml = currentHtml;
               console.log(`[websiteGenerator] Using HTML from tool parameter.`);
           } else if (latestHtml) {
               workingHtml = latestHtml;
               console.log(`[websiteGenerator] Using HTML from latestHtml state.`);
           } else {
               console.log(`[websiteGenerator] No existing HTML found. Will generate from scratch.`);
           }
            console.log(`[websiteGenerator] Starting HTML size: ${workingHtml ? workingHtml.length : 0} chars`);
            console.log(`[websiteGenerator] HTML preview: ${workingHtml ? workingHtml.substring(0, 100) + '...' : 'null'}`);

            try {
                console.log('[websiteGenerator] Initiating direct AI call for full HTML generation...');

                // Directly call generateText, expecting the full HTML as output
                const { text: generatedHtml } = await generateText({
                    model: anthropic('claude-3-7-sonnet-20250219'), // Model specifically for HTML generation task
                    system: websiteGenerationSystemPrompt, // Use the specific system prompt for this task
                   prompt: `Current HTML:
${workingHtml ? `\`\`\`html\n${workingHtml}\n\`\`\`` : 'null (Generate initial HTML based on instructions)'}

Update Instructions: ${updateInstructions}`,
                    // No tools needed here, expecting raw HTML output
                });

                console.log('[websiteGenerator] Direct AI call finished.');
                console.log(`[websiteGenerator] Generated HTML length: ${generatedHtml?.length || 0}`);
                console.log(`[websiteGenerator] Generated HTML preview: ${generatedHtml ? generatedHtml.substring(0, 100) + '...' : 'null'}`);

                if (!generatedHtml || typeof generatedHtml !== 'string' || generatedHtml.trim() === '') {
                    console.warn('[websiteGenerator] AI did not return valid HTML content. Returning previous HTML.');
                     // Attempt to clean up potential markdown fences if AI mistakenly added them
                    const cleanedHtml = generatedHtml?.replace(/^```html\s*|\s*```$/g, '').trim();
                    if (cleanedHtml) {
                         console.log(`[websiteGenerator] Cleaned potential markdown. Final size: ${cleanedHtml.length} chars.`);
                         return { htmlContent: cleanedHtml };
                    }
                   // Return original HTML (or null if initial generation failed) if generation failed or was empty
                   return {
                       htmlContent: workingHtml, // Return the input HTML on failure
                       error: 'AI failed to generate valid HTML content.'
                   };
                }

                console.log(`[websiteGenerator] Generated HTML size: ${generatedHtml.length} chars.`);
                console.log(`[websiteGenerator] execute finished. Returning generated HTML.`);
                console.log(`[websiteGenerator] Final HTML preview: ${generatedHtml.substring(0, 100)}...`);
                // The result expected by the client
                return {
                  htmlContent: generatedHtml.trim(),
                };
            } catch (error) {
                 console.error('[websiteGenerator] Error during direct AI call:', error);
                 // Return the HTML as it was before the failed call
                 return {
                    htmlContent: workingHtml, // Return the input HTML on failure
                    error: `Failed to generate HTML: ${error instanceof Error ? error.message : String(error)}`
                };
            }
          },
        }),
      },
      maxSteps: 5, // Allow the main AI to call websiteGenerator multiple times if needed
      onError: (error) => {
        console.error("Error during main streamText:", error);
      },
    });

    return result.toDataStreamResponse();

  } catch (error) {
    console.error("ERROR in POST /api/chat:", error);
    if (error instanceof Error) {
       return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    } else {
       return new Response(JSON.stringify({ error: 'An unknown error occurred' }), { status: 500 });
    }
  }
}

// Placeholder utils removed, now importing from ./html-utils.ts